UNO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uno.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uno/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.empleo, name="empleo"),
    path('trabajador/<int:id>', views.trabajador, name="trabajador")
]

uno/models.py
from django.db import models
from datetime import date
import uuid

# Create your models here.
class Empleo(models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.nombre

class Calificación(models.Model):
    estrellas = models.CharField(max_length=1, null=False, blank=False)

    def __str__(self):
        return self.estrellas
    
class Trabajador(models.Model):
    nombre = models.CharField(max_length=20, blank=False, null=False)
    apellido = models.CharField(max_length=30, blank=False, null=False)
    dirección = models.TextField(max_length=100, default="", null=False, blank=False)
    ci = models.IntegerField(max_length=11, blank=False, null=False)
    empresa = models.CharField(max_length=30, blank=False, null=False)
    teléfono1 = models.CharField(max_length=15, blank=False, null=False)
    teléfono2 = models.CharField(max_length=15, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    imagen = models.ImageField(upload_to="empleados/imagen", null=False, blank=False)
    domicilio = models.BooleanField(default=True, blank=False, null=False)
    descripción = models.TextField(max_length=400, null=False, blank=False, default="")
    fecha_alta = models.DateField(default=date.today, blank=False, null=False)
    empleo = models.ForeignKey(Empleo, on_delete=models.CASCADE)
    calificación = models.ForeignKey(Calificación, on_delete=models.CASCADE)
    lat = models.DecimalField(max_digits=10, decimal_places=7)
    lon = models.DecimalField(max_digits=10, decimal_places=7)
    token = models.UUIDField(default=uuid.uuid4, editable=True, unique=True)
    def save(self, *args, **kwargs):
        if not self.token:
            self.token = self._generate_token()
        super().save(*args, **kwargs)
    def _generate_token(self):
        return get_random_string(length=30)

    def __str__(self):
        txt = "Nombre: {}, Apellido: {}, CI: {}"
        return txt.format(self.nombre, self.apellido, self.ci)

class Comentario(models.Model):
    nombre = models.CharField(max_length=20, blank=False, null=False, default="")
    comentario = models.TextField(max_length=400, blank=False, null=False)
    calificación = models.ForeignKey(Calificación, on_delete=models.CASCADE)
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    aprobado = models.BooleanField(default=False)

    def __str__(self):
        return self.comentario

uno/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Empleo, Comentario, Trabajador


def empleo(request):
    empleos = Empleo.objects.filter(nombre__icontains=request.GET.get('search', ''))
    context = {
        'empleos': empleos,
    }
    return render(request, 'uno/empleos.html', context)

def trabajador(request, id):
    trabajadores = Trabajador.objects.filter(empleo = id)
    context = {
        'trabajadores': trabajadores,
    }
    return render(request, 'uno/trabajadores.html', context)

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-es" >
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="robots" content="none, noarchive">
    <meta name="description" content="Compañía de Diseño Web">
    <meta name="keywords" content="Diseño web, pagina web, crear sitio web, una web">
    <meta name="copyright" content="T3D Design Company">
    <meta name="author" content="David A. Chentes">
    <meta name="audience" content="all">
    <meta name="description" content="Empresa de desarrollo y tecnologías web, una buena opción para todo el interesado en su presencia en línea">
    <meta name="robots" content="index, all, follow">
    <meta name="category" content="Diseño Web">  
    <meta name="telephone" content="+1 224 288 1535">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block 'refresh' %}{% endblock %}
    <title>{% block 'title' %}{% endblock %}</title>
    <link rel="icon" href="" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="{% static "js/scrollreveal.js" %}"></script>
    {% block 'styles' %}{% endblock %}
</head>
<body class="bg-light">

    {% include "layout/partials/menu.html" %}  
    
    {% block 'content' %}{% endblock %}
    
    <script>
        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                alert("Geolocation is not supported by this browser.");
            }
        }
    
        function showPosition(position) {
            var latitude = position.coords.latitude;
            var longitude = position.coords.longitude;
            
            // Aquí puedes hacer lo que desees con la latitud y longitud,
            // por ejemplo, mostrarlas en un elemento HTML específico.
            document.getElementById("latitud").innerText = "Latitud: " + latitude;
            document.getElementById("longitud").innerText = "Longitud: " + longitude;
        }
    
        // Llama a la función getLocation() cuando se carga la página para obtener la ubicación del usuario.
        window.onload = getLocation;
    </script>
    <script src="{% static "js/animacion.js" %}"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
</body>
</html>

templates/layout/partials/menu.html
<nav class="p-3 bg-success shadow">
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link text-light text-uppercase" href="#">Información</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light text-uppercase" href="{% url "empleo" %}">Busqueda</a>
        </li>
    </ul>
</nav>

templates/uno/empleos.html
{% extends "layout/base.html" %}
{% load static %}

{% block 'title'%} Empleos {% endblock %}

{% block 'content' %}

<div class="shadow p-3 bg-body-tertiary rounded pe-5 ps-5">
    <form class=" form-inline  mw-100 navbar-search" role="search" action="" method='GET'>
        <div class="input-group d-flex">
            <input class="form-control bg-light border-2 border-success small" id="search-input" name="search" type="search" placeholder="Que buscas" aria-label="Search">
            <div class="input-group-append">
                <button class="btn bg-success text-light rounded-0 rounded-end border-2 border-success" type="submit">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </div>
        <!--<div class="form-check mt-2">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
                Solo con domicilio incluido
            </label>
        </div>-->         
    </form>
    </div>

<div class="container p-4">
    
    {% for empleo in empleos %}
        <a class="text-decoration-none text-dark" href="{% url "trabajador" id=empleo.id %}">
            <div class="shadow p-3 mb-3 mt-3 bg-body-tertiary rounded d-flex justify-content-between carta"><span>{{ empleo.nombre }}</span> <span>{{ empleo.trabajador_set.all|length }}</span></div>
        </a>
    {% endfor %}

</div>
{% endblock %}

templates/uno/trabajadores.html
{% extends "layout/base.html" %}
{% load static %}

{% block 'title'%} Trabajadores {% endblock %}

{% block 'content' %}

<div class="container p-4">  

    <p id="latitud"></p>
    <p id="longitud"></p>

    {% for trabajador in trabajadores %}    
            <div class="row text-center text-md-start m-3 bg-body-tertiary rounded shadow p-3 carta" style="">
                <div class="col-12 col-md-4 order-2 order-md-1">
                    <h5 class="card-title">{{ trabajador.nombre }}</h5>
                    <p class="card-text m-1"><b>Empresa:</b> {{ trabajador.empresa }}</p>
                    <p class="card-text m-1"><b>Teléfono #1:</b> {{ trabajador.teléfono1 }}</p>
                    <p class="card-text m-1"><b>Teléfono #2:</b> {{ trabajador.teléfono2 }}</p>
                    <p class="card-text m-1"><b>Email:</b> {{ trabajador.email }}</p>
                    <p class="card-text m-1"><b>Fecha de Alta:</b> {{ trabajador.fecha_alta  }}</p>
                </div>
                <div class="col-12 col-md-4 order-3 order-md-2">
                    <p class="card-title m-1"><b>Descripción:</b> {{ trabajador.descripción }}</p>
                    <p class="card-title m-1 text-success border-bottom border-top border-3 border-success"><b class="">Distancia de usted:</b> 100m</p>
                    <p class="card-text m-1"><b>Calificación:</b> {{ trabajador.calificación }}<i class="bi bi-star-fill text-warning"></i></p>
                    <button type="button" class="btn btn-success btn-sm">Comentarios de {{ trabajador.nombre }} <i class="bi bi-chat-left-text"></i></button>
                </div>
                <div class="col-12 col-md-4 d-flex justify-content-center align-item-center order-1 order-md-3">
                    <img src="{{ trabajador.imagen.url }}" class="img-thumbnail image-employ rounded-circle" alt="Imagen">
                </div>
            </div>
    {% endfor %}
    
</div>

{% endblock %}